# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:6zkoKoyKOZAV5ujud0iAZCReukDmXfEUrsW03DsaaxC3GCOOJfB//NEuLsFMfsGCpqrc83ImffAtcwo9WorWsACWa5p3ZC6eTCR86haqEDpHaUT+hvJe3pqRRD9KwSFKub/bOmaZHC4pblvWuIQ4XGkGPvCS52gbPiXWBaVDC8riAMnbV0joK7P+FiYRoq9t3ECWEnODgboV4RAiQhbQuRFfWo2Fb6iBrj3X,iv:HoSL2KmiNKHuR0C5MRcNogh/glFy3cxGakabjuglnzg=,tag:zfeU16r1bZRas4FKEDalkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-07T15:07:05Z"
    mac: ENC[AES256_GCM,data:AiXlEagGV98qM7jnhyMvn/NRzrb0bnKk/KXU5FjcLhvVm+dSB3yJMXR7g/Dl7TQ1xEqnwz6FmwkjWbPIqopwul32IcoOdzlfefeDFpOtqsteDfnUq9hpTuAO7MK9ABKy2BUpjOF7+IEj042egleIeX1l7u8u3UtE11llSRqiDcc=,iv:00ti4ju8J/efFjisqnWy+tdbda4F4vJQpNKqw6YSYUs=,tag:m0pvG4A/KEfTf7pfs4nVQg==,type:str]
    pgp:
        - created_at: "2021-11-04T21:58:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8xP0mZmqN/wAQ//VOmi+Bgt+fPsqOdS2e2GH9lm8YGOxUYTFZYH3d3fde9d
            5LkLnMYAfojymJTZgJOAqVhT1KQFh9lWyHIpPvVu4xRdrqTSvFUpU8tzGddI0tBE
            8qJie2Q8yuf9+Iu+wk2lwSWgLhiS57gAHwV+3oV7k9Trc5gTyI3hf6CNKZEC5AAj
            v74HZM02JI80CuIeFf7UrvG8QIe3COoCOfufO+tiaelbL7jCxF/mXuLCvGMSpa8T
            Nlm9L9z1F4TW2ionNXnACCiZF9X2+w6Kl57S7sXZEtmJbMLu5KW4GGR/wKnVHwT9
            4aaWO/ehbIR8y+fetOtcflgwPmajnGiWVHNFrAVwX592JnXWl0k1K+uCSrV/XxvO
            VIgBCOLWhEWcIK11MEBEGwfBZxO8oKtXDoxR8W4SPcC+T88GPJ3VNXGqLgg67T19
            ZIvl+hs/fJyLCAJQGMG5qPRq0uAAM4Z2uHztrti43mcQmbDR2CepQzt2Li1ZidqV
            fEd+irkTLH0CqRThai3N48dXIEt+9atlmPkNYNU3dqOYxthZGMMCIV0ROmKjfYlu
            3Ab4WUif5qWVUe0u/Dm/nTdtfZDPqY+ZDiiScN5YUIigvY+g7qgfq3iGS07Guah9
            BKD+qzq9DMzQUkYSfxo16c0D6ec4xKMdkGYtiTobyF3v/GJkcR0RGBY+ZwpB8XLS
            XAGO7C4pe/OgD85VxyQ1ptjZP/jDIk6JYJW4Kx926MLb0pSTWNrpA7xVgCGzNBaF
            GeJ4Uisay1rhw5N6uH7Pt0DaMvKlIZbj24479dJIBEMsi/20yabCRnT1vsAz
            =9k2T
            -----END PGP MESSAGE-----
          fp: 4EC6ACEDDDEC0607A27E1D388EC255A0E75174A2
        - created_at: "2021-11-04T21:58:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8amvocshN0zAQ/+J6x6Jmmyw8LpqHkaQAgW+Z60wf8BL3ehPm9z831xo7FO
            +Es5PO0BHZl4z7CEe0fI97g3hQZwRtVHRZgw5zPOavBNmFQy0AmmXkE9I/TS+4RM
            kxTXpzU1L0aZXHVN7dkqj/rigSYZAxLT7HPChGUW8cqXaVQ6/n4zHJbGKnpj4ROb
            FGcL4WXqJYXbxTaOz0l5l0Mpsn7GL1+jF212gGJfqoiSC1zf5RfkHZZ8stKH1rrc
            ev4Xu+WBuvdQpDp14O0ha2TcpGbfnIx0kWEG8YwTpkOEQqkhcS6mc8Cjfuj4sos5
            sDBCM97c6kK21SGUJktvjDm4QY/OFAzTk6S03baQKRFjMdthwbnuZyVfb2QWPoo8
            +K6C5dGHw4+eD/83NKZwyoIl+nRrZHQu1qv/7IhR0vylqWglETjc3ZKfnJP5KuZ3
            HJ2Hw2yMFKWOov8toiblG1k8uoH5I+XjbAsb/KaaRWAIGzQf/+owwKylr5MfHoyd
            wP0D+yGuCcB160JGsqHUGWoZq8mVOPNCDbIw0zmE9eDpREp8j7nMdSQwXVLNRRjA
            72ETSO/GhCOnb1iuQVuvKOtvpr/xng96IUZWSoNKTd6pat/W9YlHG1k9bAP1w+xZ
            uENLQDAWgxGgmWNr9j/Eoe8+9wmU1X2QwICrIQYkLcNUIUys9fQjPN7OTQNsVV/S
            XAEiucNVa63GPdjUArreVfVQejlafCcH/2g+yxHuTlPr9Tc7xOLAJs98NmD8t0Xt
            G9bwu8HzpKepL1AfVJ/G4ET1grMMezGNZ9VUZxWdpAGD6uv9aiLBThU3sN2m
            =iz2W
            -----END PGP MESSAGE-----
          fp: 0E0509990CEB83F085FC9D0CC7E812118429FDF3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
