# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:SkW1kZYa49XPr4qC7sm/P8uYXgD6w9fIOpOc5krQt5MRMdrALowN5Vkugim5zhTg1Ajxzj56EFOW3yAoMH7lRI/kyJYqHzkfS1mEp1SLlCKRWI2MJuQZXcDHaNZrrL5KUtw0X6A9P0sT4z2qCJDxjPr/5bCMiKsR,iv:ImLhvShLSSVSfTbx+wc+OtZb4vnBYNI6KnRggHm201o=,tag:6U4yzWsul2eqoZoPqtdE2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-06T17:20:59Z"
    mac: ENC[AES256_GCM,data:Pr6bF3IMRuL1/yOMXr7nU8ZQkN+sjf1MLRzecgKnVsZjUsusp1gujMclRuJiG0aQMmwlr59XzdrLR4VMciUAg9W7AJnU/htM5Wm+ipoJO3EzwcVaeNcFMCEeA+gxjn2YCv4Be6HVa+0vw50c8uX1ZbOX1fe29vvV7qChKH39L8s=,iv:3KN/h2xaYO3+1K/f848EDiMfX+DHFALaLmpWoa+esv8=,tag:gSkFyrAz07UrV9n1J7jTIg==,type:str]
    pgp:
        - created_at: "2021-11-06T17:20:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8xP0mZmqN/wAQ//f+TJYVSn14pLlZSo9cU4CEiUo53zBc4y/o8BWI1rAAC9
            tnaWQFN+/2tRo78l5U7vIYQdZIc9MXIIrbcLNUzzSzFF3fN9T+Y0EvLmUMn1bXKQ
            BgFlSp9s+zplWJEl0vo+mKQOTilnOabjnhVSeYUgV4ySofRlIWg2DYCPqrGtxqKV
            lr/1BDzwxjVPyedfW/Vu0+dnVa8NMAVsGEC/wyRJFHSjYuAdKZ3i9xIwu2OttD68
            2UEyIHZIGpDFaYbD1oluq2nI5LEBoJPnPF4kzPRzF6trlFcmyTNMWBvSF6sS6QrY
            b9BHPlMw3bbpjOEgqvRKStFPeRE4sGPbjDjNQh7wwYP+kVLW6Dfheq/3DlkALQrq
            UdVoEuFpQojT+h2THqaUhP4Ts0+uSp39cJLIKazpaYxwUaH9Zep98W8HE3dwquld
            HnJ7orY8DH98pPS6TbZ8xreNtSPmmJxQ60Nn/CwlewMeO1bn4BIM1wP1Z4CIjUuM
            5WPDyqNT0mvKMoNs0tUbMzwdekqyyhDUsbVPIDsH04wnR33fnOt7HQMPWI0rrl6Q
            tNfcz8POBenjPr97H6BNLYSa4e0lviaHLrGfpYCp8sbgHb29s17yvEv1wULkbY4L
            979QGtEkv1RgBf8VtDO9PFwQS8Ysmc9wMQp8H31VOAHHMj7xvcmy2ew2wzriUYLS
            XgE2ztXV9Fku7UQEWQ9NmHbg4p8p0QBEqPt2ThvHiFlxGRX58xXjpVRWbUUsE6a7
            OAM/4RW0IXRHB7OVyRXA1+AiekBQ0JQBs1mAanzuvF25cMNSW1aRwUVsxPbMo1M=
            =KF08
            -----END PGP MESSAGE-----
          fp: 4EC6ACEDDDEC0607A27E1D388EC255A0E75174A2
        - created_at: "2021-11-06T17:20:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8amvocshN0zAQ//emTsWOe2gywKWu1XdYZgY4JCN0g+MT/vaKCWK/q6KmCU
            YMIds2k0KCLn/F6YTzvlCqw1edj8Qn1KJG1M39l7OPcVDXtNq4/YPZSe8Gab9N0t
            lX7YQfBi5t56pnRqd4UH29zZ/W/QE0bPIcyDAsXGwZ6t4e5+sEhjOq8nbvjMCmbe
            tAWON1VZ+oXG0X2yv6VhOuumb/oRTIRL+oS2hrY9i/sUtnxzESJjGgEzw2Nw4KGC
            UhClqo3gUSgWMuyI/+6vl+shQVnhMMnKW6eKxNm2KVMU9OOOj9lqQ93fTM5AaVIW
            SYTtGHENgxeBqvIObjaKfXQBuZPiJp4mbUm4Go9W6AVIdcaU2eOZtKU/CF8rTEFc
            Slre7f3UTzgh1nqcQyADsfT5oAWZR+hrRbxM7JggFFTfVqgaQa7+JOuM64LGf6Qv
            zUDmyuI8t97HprDDMUfDpaZPHR5DgojGmm7+N4mtBLS5od0slJsyXicS6Benu4+e
            PINCggCDHz0NiRYW16bvY8pBf8wNYVzhrannQd44VJR92jmpHvtgbGl7Hb4Mde+1
            aEBl3ZgDBwBvXSDuwkD5PbwJnn0wrSQ+kHgq3xsZ5ic8ynBfA6ZlFDe2HBI0XUlj
            3XkpVDXH2kbthcwaI/48iCvyEFffEBfT8TRspheXyL44lAlrI3uQLkFI/fxLRjXS
            XgFF9T6eb25JH8iDzc4ExVR4JOCka7lclOC/Tv8YT6LFhwGZY4cXM4cpCQyrrz3r
            frbCr+WC74StL3qknQ1DITQnqh0chh2/0fF+/cgul41ZEjC9MhEmI7KCHfG5aH4=
            =0/zJ
            -----END PGP MESSAGE-----
          fp: 0E0509990CEB83F085FC9D0CC7E812118429FDF3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
