---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: youtubedl-material
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: tzahi12345/youtubedl-material
      tag: "4.2"
    env:
      TZ: "${SECRET_TIMEZONE}"
      ytdl_url: "yt.${SECRET_DOMAIN}"
      title_top: "🦝 YT Downloads"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-${POD_CERT_ENV}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "video-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "yt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "yt.${SECRET_DOMAIN}"
            secretName: "youtubedl-material-tls"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: youtubedl-material-config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "${NAS_SHARE_MEDIARR}"
        mountPath: "${POD_SHARE_MEDIARR}"
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    podAnnotations:
      useVpnGateway: "true"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:    
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                    - "true"
