---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-config
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
