---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-dns
  - intel-gpu-plugin
  - metrics-server
  - nfs-subdir-external-provisioner
  - node-feature-discovery
  - reloader
