---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  #
  NAS_ADDR: "192.168.53.80"
  NAS_SHARE_MEDIARR: "/mnt/superstore/mediarr"
  NAS_SHARE_MINIO: "/mnt/superstore/minio"
  NAS_SHARE_PHOTOS: "/mnt/superstore/photos"
  NAS_SHARE_SURVEILLANCE: "/mnt/superstore/surveillance"
  NAS_SHARE_WIKIJS: "/mnt/superstore/wikijs"
  #
  METALLB_LB_RANGE: "192.168.88.1-192.168.88.244"
  METALLB_TRAEFIK_ADDR: "192.168.88.1"
  METALLB_SYSLOG_ADDR: "192.168.88.2"
  METALLB_PLEX_ADDR: "192.168.88.5"
  METALLB_QBITTORRENT_ADDR: "192.168.88.6"
  METALLB_HASS_ADDR: "192.168.88.7"
  METALLB_EMQX_ADDR: "192.168.88.8"
  #
  NETWORK_MANAGEMENT_CIDR: "192.168.0.0/16"
  #
  K8S_CLUSTER_CIDR: "10.42.0.0/16"
  K8S_SERVICE_CIDR: "10.43.0.0/16"
  #
  POD_SHARE_MEDIARR: "/media"
  POD_SHARE_PHOTOS: "/photos"
  POD_CERT_ENV: "production" # staging/production
  #
  VPN_GATEWAY_PORT: "1194"
  VPN_PORT_QB: "56059"
  #
  POSTGRES_ADDR: "192.168.53.90"
  POSTGRES_PORT: "5432"
  #
  COREDNS_ADDR: "192.168.53.30"
  #
  UNIFI_ADDR: "192.168.53.30"
