---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - overseerr
  - prowlarr
  - qbittorrent
  - radarr
  - readarr
  - sabnzbd
  - sonarr
  - youtubedl-material
