---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - downloads
  - external
  - home-automation
  - kube-system
  - media
  - monitoring
  - networking
  - security
  - services
  - system-upgrade
  - tools
  - vpn-gateway
