apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: snapshotgroups.gemini.fairwinds.com
spec:
  conversion:
    strategy: None
  group: gemini.fairwinds.com
  names:
    kind: SnapshotGroup
    listKind: SnapshotGroupList
    plural: snapshotgroups
    singular: snapshotgroup
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: SnapshotGroup
    listKind: SnapshotGroupList
    plural: snapshotgroups
    singular: snapshotgroup
  conditions:
  - lastTransitionTime: "2021-11-15T14:19:59Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  - lastTransitionTime: "2021-11-15T14:19:59Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-11-15T14:19:59Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1