# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: networking
stringData:
    users: ENC[AES256_GCM,data:rq+Eiw==,iv:ywC0M9TQI2yh2XBWol5smF8aBCwo+xHAEqU7QHEtxck=,tag:dj9jLWFTkJ42uppX/xFcLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-10T16:22:38Z"
    mac: ENC[AES256_GCM,data:GTXQuwACZKiDGLK3CWMtpU75qIQmdwZI8vavAQwY0Q6X74ldO+MMdczFk2WqtFDi3HTRjEciVdKS9DZFKhLAsIYtwA/0lRY5Z8hStcEUOgNDaJSu9Nal0CCOvKskz8S9B4FiYOWG1VvWhk927e8fuS5ddOhB/ZMt2CwRbL9p5VI=,iv:Sy7b8Dy2Sv1XTJWJFcifFghmXeariHhZm1rRM16nSqM=,tag:WZXBXsKQ3flKO65XTWvRZQ==,type:str]
    pgp:
        - created_at: "2021-10-10T17:16:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8xP0mZmqN/wARAAk/lNYdvLwP4ggiclDtpIRZ5ltzif+w4ngMm6HC6lJ68D
            GmRW0za4XVRQ0SEJoUq7FHnLOi39hNFhQfw2NVYLoX08w6t5k7fNYDaUHxdKWU+Z
            Fzs6JlCpbAT0cz2coVkuGImmtMHmSOmaZo7bt+5LKIdKZ4CgBRbRl1s0WZpkQhRq
            SuiJWxEkJZVQVfFPUioiSRVjS7SuE/taMCSAPS8GRN7st/BC6rkSWU4U8afLLZGA
            mEvjjcxm9oEZIOL++glEQUS5niq6Lq+D6XKAQYHzMGrKjHPy7MlFSE3IPxORfSJH
            TSQ+vdEC/iZhvfhNzkkWla47MZzotrduor42tdD7VW/faIsHgfXO2R7QP9iHACOQ
            nVlGnpu6P9rYsbor0ZrEFW0jVHl+12Eoee3w86LJda75krwsB9weMDfYg9UaEL45
            Gc0DMQkw3ANYWNIcGG1wWkQgXBpi9wuZIZQUXO+LGACkuZVoWU6AZbNkEFdcKf6Q
            wHftOCtl4l1W8F5XwYzKxvAfD6rno4xuJ713OY+1CHeHn86pn1BLnRf5g/3Ytpig
            qLvcISvLCZ4UT4Mh9EuhYA3JGb6BblCnJTe0U/XybUrrnbR+LXX8PZdx5USIM8P2
            utrcpd2QdgHQmhSPKjwUPaKn1xTpftznFd0XKSJRUXGl/gUN1aSNhYOfuCGc0sTS
            XgHfXFP5tuozwoZQv12ektMoky+m3NnigFzQndLSCJrbkp3N7ry89of9v0A8osak
            Q1ZL7TAVojZGB0UfLDtLoj7WJHJPXXbp8OS39mG03tXUESl2uYPZsiaMhUPqSMY=
            =SnrC
            -----END PGP MESSAGE-----
          fp: 4EC6ACEDDDEC0607A27E1D388EC255A0E75174A2
        - created_at: "2021-10-10T17:16:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8amvocshN0zARAAl+nGatOfIl4UNhJbG/ym5C8qUWPCh3W8eI6p1LrH8h2I
            6E7BIXyBGWUL8feThv9/llDfOmF1BNI+Hvih31rDECHdfUEHdb1YhzubI5rJ2sm7
            ZWUXS6DUoE+pyGH9HHK2rIOiKITUeQSo3f4UhyU1TSGKu7fqvGB2Fr3m0S60iZpg
            a12ROhiM7W8HglmUCiSgX8m/jb6OOkorJBxTg1O0rdn4Ixboeuh2EBJ0QPmvY09P
            HerVXuBrrALn47gBrs9bb6MpvuZlkAAoO8m+zz053wnioe1J26CfjGTA2k+6Z5Qa
            icyz1FiYgRhwZz3l7rS+ibU2Ok8/Do793hvOEKWNCEApe/RTfE88tdvlY1DDQtDb
            WmCCbj/4ZwBKnsZFDlI1eKV4q+a7FJRudRzsG4Vwkdm9m1JlhAcuyq9Ffe/VunnK
            KjvCPU+iORA27CLNrNNu5IhO2o0rrwy+Lrf08vxZ3O78BDAkkQjvWpvZz8LzWm9n
            Pq3gDsAOtt766RhI1zwEnbmtt9UJQC0VKjmkRBMS80KMV5ypkHQ0nSAxRlF3Ylvv
            TOASaPITlzpFQCRw44D3bP1XNIvSwoBqSBBjmLdj8itnH6JGWQ3UtQRQdaWnjYy6
            gt0K0vHnIhLH3K3BTfqRZOaEd0xVg0/hboKhCVF2LwbTl/q7vvcws4se5EwbB07S
            XgGIp50EsLCkMPUbfzQITDziDK4fUXqgFdm1dZYHgz74EVg6RPNnsIpQQi4FKY+S
            VHNWuAQdqv/KL5mn5EsUHa43+xVxmorulJ0QhzwoKNxUkqanps1mQAqkZ9H2jSM=
            =fBYH
            -----END PGP MESSAGE-----
          fp: 0E0509990CEB83F085FC9D0CC7E812118429FDF3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
