---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.27.0
    env:
      TZ: "${SECRET_TIMEZONE}"
      LOG_LEVEL: "info"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-${POD_CERT_ENV}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "requests.${SECRET_DOMAIN}"
            secretName: "overseerr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:    
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                    - "true"
