---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: protonmail-bridge
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: protonmail-bridge
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: shenxn/protonmail-bridge
      tag: 1.8.12-1
    env:
      TZ: "${SECRET_TIMEZONE}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-${POD_CERT_ENV}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "email-lock"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: p-bridge.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - p-bridge.${SECRET_DOMAIN}
            secretName: "protonmail-bridge-tls"
    persistence:
      config:
        enabled: true
        existingClaim: protonmail-bridge-config
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:    
                - key: node-role.kubernetes.io/master
                  operator: NotIn
                  values:
                    - "true"