# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:GhO5J+ovE6VTdcX/wMEdHz+T2p9p63ObB5KPNbpvMuOnWz51dq4BvIfNpD5ZjorSaw3b7yJ3H5tA/nbtpEHVPEcTy72oR6YJ1ddVQj68/2DAf1oZmPZfoJ41/W+sKz9uTKaEyziFJ41/HOBXWo9wmT461Vtm8qGOa23nxfXHyCb8JaMZEXumujXTb2cUbOzvyPQtPLKCy1tK1yP1RIVdrW/0nXP1y2e7fK7d7efoAnu7HjA61Ky2QTOrpSQonIHjoU7tKXIh7yNlm8TkMNYPZWSdkgJmN4HrJmOX9HFWFV8=,iv:/tRXHQYNrL9sGlljhJQBhyAlbuR0ih2LWnacw5TSgj0=,tag:S0Xtu/lR/I8Hmx6jUiaxpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-07T12:30:49Z"
    mac: ENC[AES256_GCM,data:u8OrBs3yRTZEzgSD3W/01phwAvyyHKmJ7RrwtImS2KAgRpWVxw4Jw1jqrtDZdqwVBzh1PntZPwvk8PxEI0GpeZhZb06JIljUy430tkrY/wlbXlBMRfdV8nXxPsuMWZOoqIw6GlhVrJw5itshoW0rU8cniCMaZuwAwwdNe/sxu2k=,iv:K1wKQsme4vYHfEWmt/Thr8aKAwTzB5kBlCTR6vuwp3I=,tag:t2Zw3klcVo/bFkxu+Qe1Aw==,type:str]
    pgp:
        - created_at: "2021-11-07T12:30:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8xP0mZmqN/wAQ//dykBq2IlAxbK7hzNW0p2zGur0MtiEUlDDzumcNYOuE2c
            QYq1X88VTRBafz6CQksClu2tb+T/DJjTsNxEXso/T4rWwtETg5vceXeOYeMWmsm9
            WleoDhJIDidJK3t2t3o0iOseq3uF99jf/Mpq//OR+xAdGYPTx1VP1aqprIHYES5H
            8808HdZP7aIgNPGsKUEZd/6VkcFShat513fhouc8xrE48cfXKr8xpZKpDShaSSme
            3SO/DQR4OZzt/0+FYeqo/mj8pvlfUumDtDOe4P99k93PXN8ePBxWcsoPkavC42ze
            H4QHE6Qd/n3fEGLRohtIg+dIZSNZYZ2QzcgnxIV3q/1p+KGuXEPJ8PseEbkedvbc
            6aw3XTxBCYg2j44IyzWXVbBwJIIufiKE4b849FQ9oImf4RK5v7nhwhDYeT/YPPoq
            TSi3IaKhIU+SM9C7KcExfsi25s4MbhxiAnXIt2aFHLL3QBGGvq/f/fkGJfojixQ4
            AQwWf/+1qK/IVEyzwGixBFRYLuvsQuwQTNqF2zaiimTt3mhMwmDV+XuFB5NZ82Wc
            xUmbu+NcQdr5UYzlCRchcqT7i7Z+Jywi5vm6xua4IuKa83fV4O9LR+xOsKUhE2TE
            mH/edHrVLgZjXfd142bkrTB39yAsaTDMz9XLsBRwQ/0CVVlsx4G+mHzwNsS71vDS
            XgH+i/OPBl7rn6Zjl//RPGwxxnWNGEgy830Hg+jes8kLm3O5X5bodp1JaRztZiAJ
            sIHB0hDsZT5mpxlMIUKVWZq84fL1q2JRaq9HxKsypMeUfJ5MQnXmA6UGhKP94EA=
            =5lAM
            -----END PGP MESSAGE-----
          fp: 4EC6ACEDDDEC0607A27E1D388EC255A0E75174A2
        - created_at: "2021-11-07T12:30:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8amvocshN0zAQ//bE21diN9sJciY+Rb3Y+g30495Lr1Q7eLOLEvKceePsYo
            mJ3p7PmR9U1gXgjgspLh0/TLfOOH/UP5rHH45uQuyfv3x4xRDLVIC8A/hsjXxS32
            nu4KQiG1kBoXJBsLepPaLVea+CsXSJGG8lhNO3Emo89AYjL3O7+J3pfgb+MI2Efj
            3c42t1ta7IoOpeEdiRS+aLSZ2c1RswOKsU3oUIuw4TyeI6Yn/dePD/rjr9qRgPmD
            Hvk7af2AjE35bKx4cKybFfBc7kXSj7biZTMr2lT12AVmi1y7rg1CEdeYRvDumQEG
            ors1pS1N+TvoUEenrL0Yj9iBMiKqcgroQBJfvL/QmLsrlJT98b6XhLAkwG3Y90P8
            UdnPgBJpdSOSQYyIFILqRwKjW8Q/c5lP+pqbJ5be1aCSdLX33Xc+3l7yv0z3+Vun
            KYmGspYtEvoeo0eqIpzd1MUpijGenG+YsiLgZYDvMIGld8EfyorXiEfCRPAO17ck
            use/3KXNH4fXRjZuKQwj92o+Ns7NcIPwbjmr04dBbHk5Tsxy/z8FFcDThRrrw/8o
            +UXfBrW3DxT4kNxJVHC8UWg8h6d07mul48mJcjjtah2eeHVNHXUi6psyjZUIjPaX
            RtXH3NcCGUlPmPn1MLAahcZVaBvA+mMiBt5nt9XxFIrI5nbF/fN9e9v2msJxe3DS
            XgH+VSyqBd1PnI8mj4kclBXqq3SRdyCruJNT2kwOEd7qd6gYGBUCEroHuEyweXH9
            5w/Err+zCl7JhiJ/TWyGknMBXl1POWJSsll9bgelQ2VHGPtq/OAa8qBQy1MrxLY=
            =JIT/
            -----END PGP MESSAGE-----
          fp: 0E0509990CEB83F085FC9D0CC7E812118429FDF3
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
